
matrix:
  include:
    # gcc build
    - os:               linux
      name:             Linux Build (Bionic)
      dist:             bionic
      language:         cpp
      addons:
        apt:
          sources:
          - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
          packages:
          - qt512-meta-minimal
          - qt512multimedia
          - qt512svg
          - libboost-dev
          - libgl1-mesa-dev
          - libboost-system-dev
          - libboost-filesystem-dev
          - libgtk2.0-dev

      install:
        - sh ./.CI/InstallQTStylePlugins.sh

      script:
        - dateOfBuild="CHATTERINO_NIGHTLY_VERSION_STRING=\"\\\"$(date +%d.%m.%Y)\\\"\""
        - /opt/qt512/bin/qmake CONFIG+=release PREFIX=/usr DEFINES+=$dateOfBuild
        - make -j$(nproc)

      before_deploy:
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=nightly-build
        - git tag $GIT_TAG -f
        - sh ./.CI/CreateAppImage.sh

      deploy:
       skip_cleanup:    true
       overwrite:       true
       provider:        releases
       api_key:
           secure:      ZzS55wlwtLAVEBaDDMqiuqZwuTpvLbNnaNw0enfiqpjWT7hgbbp/SBw2rbYIkVqm7tBHCLnEzKto6p4Gz6ROo0gGACARmx7EwIloX18rMCuBWygNHRyVruDSlmEOLWRqYByDbUdCkKhYr9aegnkm7zhzCmSBCTW28/uVlxM2bTHIgqKEpB4k1W8OqKdJDxqZKeF4r7nDNSOx5ylhpiK+WNFK8yfiaF1SQlSwsdv9o1RkbJlew7iigvHvEM2kDMkiMWYlJ2khkUWVCVQDQGe4/ya5pgTIHDLu5sZuclp5zhgfDf1U3STvsbQWvxJfsmCId7IQHJ83OSFeoUf6y849i3GMqlNi3aXrxEx0fi0dILQ76/Sj246FPMA4kC0/W49uaxqD784wFuJDjSWeWwi/NPoJ/gz0mGZy+08BoztOGqqOKjJJdESBYTio71N8VcK09zQ0LjXRmX+g3BbrK6a2F3hiMKeuYwdaN2/KdMMoqFDau6L3fXLdpcHKdJC8K/yzJtyyIe0CRB2nj8sZLHfxDwoRm7gOTDXq1zPL7CP9cCwCnCR6nm3CqUW/CnSWuMKpSoQRlP5EBI7zzYT2/tZc/vat5nob7Xif6yFF9fh/VHx4tC6zsfkA1nPPN3+QpdVInRo7dCVxtTqey5FdVjSiv7n11TrFhZ7+Fr5x6CZqa58=
       file:            "Chatterino-x86_64.AppImage"
       prerelease:      true
       on:
         branch:        master

    - os:               osx
      osx_image:        xcode11
      name:             xcode Build
      compiler:         clang

      addons:
        homebrew:
          packages:
          - boost
          - openssl
          - rapidjson
          - qt
          - p7zip
          - create-dmg

      script:
        - mkdir build && cd build
        - dateOfBuild="CHATTERINO_NIGHTLY_VERSION_STRING=\"\\\"$(date +%d.%m.%Y)\\\"\""
        - /usr/local/opt/qt/bin/qmake .. DEFINES+=$dateOfBuild && make -j8
        - /usr/local/opt/qt/bin/macdeployqt chatterino.app -dmg
        - mkdir app
        - hdiutil attach chatterino.dmg
        - cp -r /Volumes/chatterino/chatterino.app app/
        - "create-dmg \
          --volname Chatterino2 \
          --volicon ../resources/chatterino.icns \
          --icon-size 50 \
          --app-drop-link 0 0 \
          --format UDBZ \
          chatterino-osx.dmg app/"

      before_deploy:
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=nightly-build
        - git tag $GIT_TAG -f

      deploy:
        skip_cleanup:   true
        overwrite:      true
        provider:       releases
        api_key:
            secure:     ZzS55wlwtLAVEBaDDMqiuqZwuTpvLbNnaNw0enfiqpjWT7hgbbp/SBw2rbYIkVqm7tBHCLnEzKto6p4Gz6ROo0gGACARmx7EwIloX18rMCuBWygNHRyVruDSlmEOLWRqYByDbUdCkKhYr9aegnkm7zhzCmSBCTW28/uVlxM2bTHIgqKEpB4k1W8OqKdJDxqZKeF4r7nDNSOx5ylhpiK+WNFK8yfiaF1SQlSwsdv9o1RkbJlew7iigvHvEM2kDMkiMWYlJ2khkUWVCVQDQGe4/ya5pgTIHDLu5sZuclp5zhgfDf1U3STvsbQWvxJfsmCId7IQHJ83OSFeoUf6y849i3GMqlNi3aXrxEx0fi0dILQ76/Sj246FPMA4kC0/W49uaxqD784wFuJDjSWeWwi/NPoJ/gz0mGZy+08BoztOGqqOKjJJdESBYTio71N8VcK09zQ0LjXRmX+g3BbrK6a2F3hiMKeuYwdaN2/KdMMoqFDau6L3fXLdpcHKdJC8K/yzJtyyIe0CRB2nj8sZLHfxDwoRm7gOTDXq1zPL7CP9cCwCnCR6nm3CqUW/CnSWuMKpSoQRlP5EBI7zzYT2/tZc/vat5nob7Xif6yFF9fh/VHx4tC6zsfkA1nPPN3+QpdVInRo7dCVxtTqey5FdVjSiv7n11TrFhZ7+Fr5x6CZqa58=
        file:           "chatterino-osx.dmg"
        prerelease:     true
        on:
          branch:       master
