# SPDX-FileCopyrightText: 2025 Rasmus Karlsson <rasmus.karlsson@pajlada.com>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "chatterino"
SPDX-PackageDownloadLocation = "https://chatterino.com/"

# [[annotations]]
# License files we embed for display to users
# XXX: How do we license these?
# path = "resources/licenses/*.txt"
